export const ActionTypes = {
    INIT_LOCATIONS: 'INIT_LOCATIONS',
    INIT_FACTORIES: 'INIT_FACTORIES',
    SET_NAV_ITEM: 'SET_NAV_ITEM',
    SET_LOCATION: 'SET_LOCATION',
    SET_FACTORY: 'SET_FACTORY',
    SET_SELECTED_LOCATION: 'SET_SELECTED_LOCATION',
    SET_SELECTED_FACTORY: 'SET_SELECTED_FACTORY',
    UPDATE_LOCATION: 'UPDATE_LOCATION',
    UPDATE_FACTORY: 'UPDATE_FACTORY',
    LOADING_LOCATION_DATA: 'LOADING_LOCATION_DATA',
    LOADING_FACTORY_DATA: 'LOADING_FACTORY_DATA',
    LOCATION_ERROR: 'LOCATION_ERROR',
    FACTORY_ERROR: 'FACTORY_ERROR',
    SELECT_MANAGER: 'SELECT_MANAGER',
    HISTORY_ELEMENT: 'HISTORY_ELEMENT',

}